baseurl: "/"
title: Partido Migala
theme: 
languageCode: es-mx
copyright: Migala

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: My headline
  description: My description
  opengraph: true
  logo: img/semilla.webp

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Sobre el proyecto
      url: /page/proyecto
      weight: 1
    - name: Horizontalidad
      url: /page/horizontalidad
      weight: 4

site:
  author:
    - name: Kevin