timeout: 30000
enableInlineShortcodes: true

taxonomies:
  category: categories
  tag: tags
  group: group
  author: authors

privacy:
  twitter:
    disabled: false
    enableDNT: true
    simple: true
    disableInlineCSS: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true