baseurl: "/"
title: Partido Migala
theme: 
languageCode: es-mx
copyright: Migala

params:
  mainSections:
    - post
  intro: false
  headline: Proyecto Migala
  description: UNA REVOLUCIÓN GLOBAL, ORGULLOSAMENTE MEXICANA. Más que un partido, somos una alianza de personas con ganas de cambiar al mundo. La política es sólo otra herramienta.
  opengraph: true
  logo: img/semilla.webp
  dateFormat: "Mon, Jan 2, 2006"

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Sobre el proyecto
      url: /page/proyecto
      weight: 1
    - name: Horizontalidad
      url: /page/horizontalidad
      weight: 4

site:
  author:
    - name: Kevin